apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
spec:
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      name: frontend
      port: 80
      targetPort: 80
    - protocol: TCP
      name: api
      port: 8080
      targetPort: 8080
  type: LoadBalancer
