apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: my-backend-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080 # Wewnątrz kontenera
  type: NodePort
